### PR TITLE
automatically determine API endpoint host

### PR DESCRIPTION
**Pull request by trevharmon**
In order to make these scripts a little more general, this commit uses
`puppet config print` in order to determine the most likely host for the
API endpoint. Granted, one could still go in and hard-code the desired
value into the script.

### CODE REVIEW

**Comment by glarizza** [comment]
I appreciate you standardizing on this for me :)  This DOES lock them to whatever is set in the 'server' field of puppet.conf, which may not be correct (especially with console or puppetdb nodes), so I'm torn as to whether to accept this or not.  

How about something like this:

``` shell
SET_SERVER=$(puppet config print server)
CONSOLE="${CONSOLE:-$SET_SERVER}"
```

This would allow someone to do `CONSOLE=my.puppet.master ./script.sh` and set it inline without having to modify anything - does that sound like a plan?

**Comment by trevharmon** [comment]
Sounds good. I'll make the suggested updates.

**Comment by trevharmon** [comment]
@glarizza, updated the PR as requested.

**Comment by glarizza** [comment]
That's awesome, @trevharmon - thanks again!

**Pull request merged**
