### PR TITLE
Update to take class name from argv

### PR DESCRIPTION
**Pull request by gabe-sky**
This script is way easier to use if it takes the class name from argv.  So, now it does.

### CODE REVIEW

**Comment by natemccurdy** [comment]
👍 

ping @glarizza for merge.... I thought I had write access to this, but I guess not.

**Comment by glarizza** [comment]
@natemccurdy You do now :)  I'm actually not a big fan of introducing JQ into the command because not everyone has it. The rest is all good.

**Comment by natemccurdy** [comment]
@gabe-sky You could switch to PQL and that would lessen the need for `jq`:

```shell
--data-urlencode 'query=resources[certname] { type = "Class" and title = "${CLASS_NAME}"}' \
```

**Comment by gabe-sky** [comment]
In a hurry, so I just switched back to python for the json tools.

**Pull request merged**
